source :rubygems

gem 'rake', '>= 0.9.2'

gem 'sinatra', '>= 1.2.6'
gem 'shotgun', '>= 0.9'

gem 'coffee-script', '>= 2.2.0'
gem 'erubis', '>= 2.7.0'
gem 'sass', '>= 3.1.7'
gem 'therubyracer', '>= 0.9.4'
