# Link configuration parameters
#SAMPLES_PER_SECOND = 48000
#CARRIER_CYCLES_PER_SECOND = 500
#SAMPLES_PER_CARRIER = int(SAMPLES_PER_SECOND/CARRIER_CYCLES_PER_SECOND)
AMPLITUDE = 0.5
CHANNELS = 1
